{% set version = "0.25.0" %}

package:
  name: "xtensor"
  version: {{ version }}

source:
  url: https://github.com/xtensor-stack/xtensor/archive/{{ version }}.tar.gz
  sha256: f5f42267d850f781d71097b50567a480a82cd6875a5ec3e6238555e0ef987dc6

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - xtl >=0.8,<0.9
  run:
    - xtl >=0.8,<0.9
  run_constrained:
    - xsimd >=13.2.0,<14

test:
  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/conxtainers/xarray.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor\containers\xarray.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtensor\xtensorConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtensor\xtensorConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The C++ tensor algebra library
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: https://xtensor.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
